version: 2

build:
  image: latest

sphinx:
  builder: html
  configuration: conf.py
  fail_on_warning: true

sphinx:
  configuration: docs/conf.py

python:
  version: 3.7
  install:
    - requirements: ./requirements.txt
