version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.7"

sphinx:
  builder: html
  configuration: conf.py
  fail_on_warning: true

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: ./requirements.txt
